[package]
name = "lean-scheme"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "33df7e88ddc7b9629348615ef06b2d2f8446b192"}
